import '@/app/styling/main.scss';

import type { Metadata } from 'next'

import ConnectSocket from './internals/socket/ConnectSocket';
import ToastMessageContext from './internals/toast-messages/ToastMessageContext';

export const metadata: Metadata = {
  title: 'Online Gaming Platform',
  description: 'Generated by create next ap',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ConnectSocket>
          <ToastMessageContext>
            {children}
          </ToastMessageContext>
        </ConnectSocket>
      </body>
    </html>
  )
}
